# Generated by Django 3.0.2 on 2020-02-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20200217_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='invoice_date',
        ),
        migrations.AlterField(
            model_name='status',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Billing'),
        ),
    ]
