# Generated by Django 3.0.2 on 2020-04-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20200217_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='status',
            name='invoice',
        ),
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.BooleanField(choices=[(1, 'PAID'), (0, 'UNPAID')], default=0),
        ),
        migrations.AlterField(
            model_name='billing',
            name='buyer',
            field=models.CharField(choices=[('JILA', 'JILA MD UNION TEST ADDREESS \n GST NO : !12343557 \n TESTING')], max_length=300),
        ),
        migrations.AlterField(
            model_name='billing',
            name='seller',
            field=models.CharField(choices=[('PARESH', 'PARESHTRADERS SELLER SELECTED \n BHOPAL \n \n (*@^)%!#@@ ')], max_length=300),
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
