# Generated by Django 3.0.2 on 2020-04-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20200425_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='buyer',
            field=models.TextField(choices=[('JILA', 'JILA MD UNION TEST ADDREESS \n GST NO : !12343557 \n TESTING')]),
        ),
        migrations.AlterField(
            model_name='billing',
            name='seller',
            field=models.TextField(choices=[('PARESH', 'PARESHTRADERS SELLER SELECTED \n BHOPAL \n \n (*@^)%!#@@ ')]),
        ),
    ]
