# Generated by Django 3.0.2 on 2020-04-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20200425_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='products',
            name='total',
        ),
        migrations.RemoveField(
            model_name='products',
            name='words',
        ),
        migrations.AddField(
            model_name='billing',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='billing',
            name='gst',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='sub_total',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='total',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='words',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
