# Generated by Django 3.0.2 on 2020-04-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20200425_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='buyer',
            field=models.TextField(choices=[('JILA MD UNION TEST ADDREESS \n GST NO : !12343557 \n TESTING', 'Jila')]),
        ),
    ]
