# Generated by Django 3.0.2 on 2020-04-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20200425_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.BooleanField(choices=[('U', 'UNPAID'), ('P', 'PAID')]),
        ),
    ]
